### PR TITLE
Automation of list creation & add parallelism

### PR DESCRIPTION
**Pull request by mirdukkkkk**
GitHub Workflow has been added, which creates the lists itself and releases it to Releases (you can see how it works [here](https://github.com/mirdukkkkk/singbox-ech-list/actions/runs/11612748256)). Also added checking for dependencies (jq, parallel, wget).

### CODE REVIEW

**Comment by Sandile225325** [comment]
Отгрызи свои яйца

**Comment by mirdukkkkk** [comment]
What is the parallelism added for? 
I think the answer is clear, but I didn't even wait for the first worker to run because it was collecting data for more than **3 hours** ([link](https://github.com/mirdukkkkk/singbox-ech-list/actions/runs/11609997975)), so I just canceled the task
Whereas the worker with added parallelism is 40 minutes ([link](https://github.com/mirdukkkkk/singbox-ech-list/actions/runs/11612748256))

I think you can see the difference

**Comment by Akiyamov** [comment]
Hi, i understand why parallelism was added since this script is running in jenkins everyday for 4 hours, also that's why i didn't use GH actions. I think that some things can be changed, i will write some things that may be better. If you don't want to fix it just write, i will do it myself

**Comment by mirdukkkkk** [comment]
I can try to do it myself. I'd love to hear a list of edits you'd like to see!

**Comment by Akiyamov** [comment]
Fixed those things by myself since i want to add xray rn so i don't really won't to bother you. Big thanks to you, will leave a note about you in repository

**Pull request merged**
